export const MARITAL_STATUS = [
  { label: 'Solteiro(a)', value: 'Solteiro(a)' },
  { label: 'Casado(a)', value: 'Casado(a)' },
  { label: 'Separado(a)', value: 'Separado(a)' },
  { label: 'Divorciado(a)', value: 'Divorciado(a)' },
  { label: 'Viúvo(a)', value: 'Viúvo(a)' }
] as const

export const BRAZILIAN_STATES = [
  { label: 'AC', value: 'AC' },
  { label: 'AL', value: 'AL' },
  { label: 'AP', value: 'AP' },
  { label: 'AM', value: 'AM' },
  { label: 'BA', value: 'BA' },
  { label: 'CE', value: 'CE' },
  { label: 'DF', value: 'DF' },
  { label: 'ES', value: 'ES' },
  { label: 'GO', value: 'GO' },
  { label: 'MA', value: 'MA' },
  { label: 'MT', value: 'MT' },
  { label: 'MS', value: 'MS' },
  { label: 'MG', value: 'MG' },
  { label: 'PA', value: 'PA' },
  { label: 'PB', value: 'PB' },
  { label: 'PR', value: 'PR' },
  { label: 'PE', value: 'PE' },
  { label: 'PI', value: 'PI' },
  { label: 'RJ', value: 'RJ' },
  { label: 'RN', value: 'RN' },
  { label: 'RS', value: 'RS' },
  { label: 'RO', value: 'RO' },
  { label: 'RR', value: 'RR' },
  { label: 'SC', value: 'SC' },
  { label: 'SP', value: 'SP' },
  { label: 'SE', value: 'SE' },
  { label: 'TO', value: 'TO' }
] as const

export const EDUCATION_LEVEL = [
  { label: 'Fundamental - incompleto', value: 'Fundamental - incompleto' },
  { label: 'Fundamental - completo', value: 'Fundamental - completo' },
  { label: 'Médio - incompleto', value: 'Médio - incompleto' },
  { label: 'Médio - completo', value: 'Médio - completo' },
  { label: 'Superior - incompleto', value: 'Superior - incompleto' },
  { label: 'Superior - completo', value: 'Superior - completo' },
  { label: 'Pós-graduação - incompleto', value: 'Pós-graduação - incompleto' },
  { label: 'Pós-graduação - completo', value: 'Pós-graduação - completo' },
  { label: 'Mestrado - incompleto', value: 'Mestrado - incompleto' },
  { label: 'Mestrado - completo', value: 'Mestrado - completo' },
  { label: 'Doutorado - incompleto', value: 'Doutorado - incompleto' },
  { label: 'Doutorado - completo', value: 'Doutorado - completo' }
] as const

export const OCCUPATIONS = [
  { label: 'Agronomia ', value: 'Agronomia' },
  { label: 'Biotecnologia', value: 'Biotecnologia' },
  { label: 'Ecologia', value: 'Ecologia' },
  { label: 'Engenharia Ambiental', value: 'Engenharia Ambiental' },
  { label: 'Engenharia de Pesca', value: 'Engenharia de Pesca' },
  { label: 'Engenharia Hídrica', value: 'Engenharia Hídrica' },
  { label: 'Gestão Ambiental', value: 'Gestão Ambiental' },
  { label: 'Geologia', value: 'Geologia' },
  { label: 'Oceanografia', value: 'Oceanografia' },
  { label: 'Engenharia Agrícola', value: 'Engenharia Agrícola' },
  { label: 'Engenharia de Energia', value: 'Engenharia de Energia' },
  { label: 'Engenharia Florestal', value: 'Engenharia Florestal' },
  { label: 'Medicina Veterinária', value: 'Medicina Veterinária' },
  { label: 'Meteorologia', value: 'Meteorologia' },
  { label: 'Zootecnia', value: 'Zootecnia' },
  { label: 'Bioquímica', value: 'Bioquímica' },
  { label: 'Biofísica', value: 'Biofísica' },
  { label: 'Biomedicina', value: 'Biomedicina' },
  { label: 'Ciências Biológicas', value: 'Ciências Biológicas' },
  { label: 'Educação Física', value: 'Educação Física' },
  { label: 'Enfermagem', value: 'Enfermagem' },
  { label: 'Estética', value: 'Estética' },
  { label: 'Farmácia', value: 'Farmácia' },
  { label: 'Fisioterapia', value: 'Fisioterapia' },
  { label: 'Fonoaudiologia', value: 'Fonoaudiologia' },
  { label: 'Gerontologia', value: 'Gerontologia' },
  { label: 'Medicina', value: 'Medicina' },
  { label: 'Musicoterapia', value: 'Musicoterapia' },
  { label: 'Nutrição', value: 'Nutrição' },
  { label: 'Obstetrícia', value: 'Obstetrícia' },
  { label: 'Odontologia', value: 'Odontologia' },
  { label: 'Quiropraxia', value: 'Quiropraxia' },
  { label: 'Radiologia', value: 'Radiologia' },
  { label: 'Saúde Coletiva', value: 'Saúde Coletiva' },
  { label: 'Terapia Ocupacional', value: 'Terapia Ocupacional' },
  { label: 'Análise e Desenvolvimento de Sistemas', value: 'Análise e Desenvolvimento de Sistemas' },
  { label: 'Astronomia', value: 'Astronomia' },
  { label: 'Ciência da Computação', value: 'Ciência da Computação' },
  { label: 'Estatística', value: 'Estatística' },
  { label: 'Física', value: 'Física' },
  { label: 'Geofísica', value: 'Geofísica' },
  { label: 'Informática Biomédica', value: 'Informática Biomédica' },
  { label: 'Matemática', value: 'Matemática' },
  { label: 'Nanotecnologia', value: 'Nanotecnologia' },
  { label: 'Química', value: 'Química' },
  { label: 'Sistemas de Informação', value: 'Sistemas de Informação' },
  { label: 'Engenharia Aeronáutica', value: 'Engenharia Aeronáutica' },
  { label: 'Engenharia Agronômica', value: 'Engenharia Agronômica' },
  { label: 'Engenharia de Agrimensura e Cartográfica', value: 'Engenharia de Agrimensura e Cartográfica' },
  { label: 'Engenharia de Alimentos', value: 'Engenharia de Alimentos' },
  { label: 'Engenharia Ambiental e Sanitária', value: 'Engenharia Ambiental e Sanitária' },
  { label: 'Engenharia Biomédica', value: 'Engenharia Biomédica' },
  { label: 'Engenharia de Bioprocessos', value: 'Engenharia de Bioprocessos' },
  { label: 'Engenharia Civil', value: 'Engenharia Civil' },
  { label: 'Engenharia de Computação', value: 'Engenharia de Computação' },
  { label: 'Engenharia de Controle e Automação', value: 'Engenharia de Controle e Automação' },
  { label: 'Engenharia Elétrica', value: 'Engenharia Elétrica' },
  { label: 'Engenharia Eletrônica', value: 'Engenharia Eletrônica' },
  { label: 'Engenharia de Fortificação e Construção', value: 'Engenharia de Fortificação e Construção' },
  { label: 'Engenharia Mecânica', value: 'Engenharia Mecânica' },
  { label: 'Engenharia Mecânica e de Armamento', value: 'Engenharia Mecânica e de Armamento' },
  { label: 'Engenharia de Materiais', value: 'Engenharia de Materiais' },
  { label: 'Engenharia de Minas', value: 'Engenharia de Minas' },
  { label: 'Engenharia Metalúrgica', value: 'Engenharia Metalúrgica' },
  { label: 'Engenharia Naval', value: 'Engenharia Naval' },
  { label: 'Engenharia de Produção', value: 'Engenharia de Produção' },
  { label: 'Engenharia de Petróleo', value: 'Engenharia de Petróleo' },
  { label: 'Engenharia Química', value: 'Engenharia Química' },
  { label: 'Engenharia de Software', value: 'Engenharia de Software' },
  { label: 'Engenharia de Telecomunicações', value: 'Engenharia de Telecomunicações' },
  { label: 'Antropologia', value: 'Antropologia' },
  { label: 'Arqueologia', value: 'Arqueologia' },
  { label: 'Ciência Política', value: 'Ciência Política' },
  { label: 'Filosofia', value: 'Filosofia' },
  { label: 'Geografia', value: 'Geografia' },
  { label: 'História', value: 'História' },
  { label: 'Psicologia', value: 'Psicologia' },
  { label: 'Sociologia', value: 'Sociologia' },
  { label: 'Teologia', value: 'Teologia' },
  { label: 'Administração', value: 'Administração' },
  { label: 'Recursos Humanos', value: 'Recursos Humanos' },
  { label: 'Arquivologia', value: 'Arquivologia' },
  { label: 'Arquitetura e Urbanismo', value: 'Arquitetura e Urbanismo' },
  { label: 'Biblioteconomia', value: 'Biblioteconomia' },
  { label: 'Ciências Contábeis', value: 'Ciências Contábeis' },
  { label: 'Direito', value: 'Direito' },
  { label: 'Economia', value: 'Economia' },
  { label: 'Educomunicação', value: 'Educomunicação' },
  { label: 'Eventos', value: 'Eventos' },
  { label: 'Jornalismo', value: 'Jornalismo' },
  { label: 'Museologia', value: 'Museologia' },
  { label: 'Pedagogia', value: 'Pedagogia' },
  { label: 'Produção Cultural', value: 'Produção Cultural' },
  { label: 'Produção Editorial', value: 'Produção Editorial' },
  { label: 'Produção Multimídia', value: 'Produção Multimídia' },
  { label: 'Publicidade e Propaganda', value: 'Publicidade e Propaganda' },
  { label: 'Rádio e TV', value: 'Rádio e TV' },
  { label: 'Relações Internacionais', value: 'Relações Internacionais' },
  { label: 'Relações Públicas', value: 'Relações Públicas' },
  { label: 'Secretariado', value: 'Secretariado' },
  { label: 'Serviço Social', value: 'Serviço Social' },
  { label: 'Turismo', value: 'Turismo' },
  { label: 'Artes Cênicas', value: 'Artes Cênicas' },
  { label: 'Artes Plásticas', value: 'Artes Plásticas' },
  { label: 'Cinema', value: 'Cinema' },
  { label: 'Dança', value: 'Dança' },
  { label: 'Design', value: 'Design' },
  { label: 'Design de Games', value: 'Design de Games' },
  { label: 'Design Gráfico', value: 'Design Gráfico' },
  { label: 'Design de Moda', value: 'Design de Moda' },
  { label: 'Design de Interiores', value: 'Design de Interiores' },
  { label: 'Design de Produto', value: 'Design de Produto' },
  { label: 'Fotografia', value: 'Fotografia' },
  { label: 'História da Arte', value: 'História da Arte' },
  { label: 'Linguística', value: 'Linguística' },
  { label: 'Letras', value: 'Letras' },
  { label: 'Moda', value: 'Moda' },
  { label: 'Música', value: 'Música' },
  { label: 'Teatro', value: 'Teatro' },
  { label: 'Tradução e Interpretação', value: 'Tradução e Interpretação' },
  { label: 'Profissional autônomo', value: 'Profissional autônomo' }
] as const
